### PR TITLE
Fix: class function TAccountComp.EqualOperationBlocks

### PR DESCRIPTION
**Pull request by SkybuckFlying**
Compare block 1 vs block 2.

### CODE REVIEW

**Comment by ctriroli** [comment]
Could Albert comment on this? I totally agree that it should be changed if we are aiming for an equality check - but of course there might be some hidden knowledge on Alberts side if the blocknumber could be unequal in case of harforksituations or so?

**Comment by PascalCoinDev** [comment]
Totally agree with the `Result := (opBlock1.block = opBlock2.block)` fixed bug at `UAccounts.pas` **thanks SkybuckFlying, good job!**

What I don't understand is what are the extra files you're adding to root folder... Can you explain some examples of what are they used for?

Also, note, if you do a pull request to fix a bug, please INSERT ONLY the changes that fixes it, not adding extra files that someone can think are malicious extra code.... do you understand, don't?

**Comment by PascalCoinDev** [comment]
> Totally agree with the `Result := (opBlock1.block = opBlock2.block)` fixed bug at `UAccounts.pas` **thanks SkybuckFlying, good job!**
> 
> What I don't understand is what are the extra files you're adding to root folder... Can you explain some examples of what are they used for?
> 
> Also, note, if you do a pull request to fix a bug, please INSERT ONLY the changes that fixes it, not adding extra files that someone can think are malicious extra code.... do you understand, don't?

I'm open to add those extra `*.sh` files but please explain me an example of what they do in order to understand... thks

**Review by PascalCoinDev — APPROVED** [review]
Fixed comparision bug

**Comment by SkybuckFlying** [comment]
These *.sh are script files, can also be renamed to *.bat so they can be executed by ms-dos command prompt in windows.

These scripts are ment to re-create local repositories, they basically clone the github repository.

This is handy for me in case I want to try risky changes to the git repository or want to do experimental things in git or to the sources.

Prevents me from having to lookup all these git commands, it just automates it.

One script creates a normal repository which is called:

[CreatePascalCoinRepository.sh](https://github.com/SkybuckFlying/PascalCoin/blob/PascalCoinMaster/CreatePascalCoinRepository.sh)

It all creates some remotes and some branches to follow PascalCoin and PascalCoinDev github repos.

Another one is:

[CreateAdvancedRepository.sh](https://github.com/SkybuckFlying/PascalCoin/blob/PascalCoinMaster/CreateAdvancedRepository.sh)

Though I have not updated it in a while, it's probably broken but might still work, creates a mirror/repo/exact copy of my repo or whatever the url is, and allows to work with multiple checkouts (in different folders) which is very handy

My main script right now is this one, love it:
[CreateAdvancedRepositoryTabbed.sh](https://github.com/SkybuckFlying/PascalCoin/blob/PascalCoinMaster/CreateAdvancedRepositoryTabbed.sh)

^This script adds filters to automatically convert tabs to spaces and back again for faster editting of code.

And finally:

[CreateSpacesToTabsFilter.sh](https://github.com/SkybuckFlying/PascalCoin/blob/PascalCoinMaster/CreateSpacesToTabsFilter.sh)

^

Here the commands to convert tabs to spaces and back were isolated but probably doesn't work too well.

The two best scripts are:

CreatePascalCoinRepository.sh

and

CreateAdvancedRepositoryTabbed.sh

For me it's handy to have them in my main master branch so when I do any kind of git clone it auto downloads them.

So then I can get to these scripts and then I can run them again to create a more advanced git repo.

Finally here is a little video of CreatePascalCoinRepository.sh script of an earlier version how to use it:

https://youtu.be/fn6X3pAf0NE 

Maybe these two videos of git workflow can also help:

https://youtu.be/o-MCuRWZoOE 

https://youtu.be/v8YiX8tsvFs 

Bye for now,
  Skybuck.

**Comment by PascalCoinDev** [comment]
Fixed bug commit has beed added using cherry-pick process
Thanks!

**Pull request closed without merging**
