### PR TITLE
Resubmission: pip-0020.md updated to include Skybuck Flying as partial-time test engineer

### PR DESCRIPTION
**Pull request by SkybuckFlying**
Clean resubmission of this pip0020.md update based on recent PascalCoin master.

### CODE REVIEW

**Comment by SkybuckFlying** [comment]
I am still somewhat new to GIT, somehow an RSM file seem to have ended up in this commit ?!? Any idea how that happened ? It must have come from a git pull PascalCoin master...

**Comment by HermanSchoenfeld** [comment]
Hi Skybuck Flying, we could use your expertise but please coordinate in Discord. This PIP has been Withdrawn and is no longer applicable.

**Comment by SkybuckFlying** [comment]
Still interesting to investigate how this RSM file ended up there.

Bash is somewhat buggy on Windows, copy & paste of text from console windows doesn't allows work.

git commit -m "
and then some weird paste command with enter happened... maybe this caused GIT to bug or there is some other weird GIT bug.

This may confirm that GIT is a bad idea for general versioning purposes.

I am pretty sure I only copy & pasted the pip20 and yet somehow here is this weird RSM file.

I will delete this branch and try one more time to see if this weird behaviour can be reproduced or not.

But this time I tried and not cause this RSM file from appearing.

**Comment by HermanSchoenfeld** [comment]
Please join Discord to discuss - 
https://discord.gg/sJqcgtD

**Comment by SkybuckFlying** [comment]
I think there must have been an RSM file on PascalCoin master, cause it appears on left side of comparision on git... and I can't do that ?

**Comment by SkybuckFlying** [comment]
Ok this is a bit interesting, this does prove it's dangerous to blindly do git pull from a remote repository... all kinds of weird files could be downloaded... including debug files, dcus etc... interesting situation ;)

May have to find a way to prevent exe's, dcu's, rsm files from being "pulled" in, perhaps some git filter or so.

**Comment by SkybuckFlying** [comment]
Discord is too bannable... anyway why was pip20 withdrawn ?

**Pull request closed without merging**
