### PR TITLE
Multi-language support

### PR DESCRIPTION
**Pull request by CFTechno**
- minor code changes to all forms (classic gui) to automatically translate them based on select language.  
- minor code change to include\save the selected language into the settings file
- ui change in "option", added a button to select a new language, this action will show a new form (UFRMSelectLanguages) that will list all available languages (.mo files) 
- to support all this a new libraries has been added "gnugettext" which includes an updated gnugettext.pas file capable of being used in the latest versions of Lazarus. It already supported Delphi but the Lazarus parts was lacking.

PS also solved issue #199

### CODE REVIEW

**Comment by PascalCoinDev** [comment]
Please, update conflicting file: src/pascalcoin_wallet_classic.lpi

**Comment by CFTechno** [comment]
Sorry, my mistake, seems i did not commit all changes i made ( like solving issue #199 ) and a typo in UFRMOperation.pas

**Comment by PascalCoinDev** [comment]
Please note... I've noticed you included some NOT needed files (like src/libssl-1_1.dll or  *.~dsk or *.dsk ... src/pascalcoin_wallet_classic.~dsk )... I think is better to remove them from the merge...
Example: *.dsk files are desk files that can contain sensitive info about your desktop... be carefull posting those files

**Comment by CFTechno** [comment]
you are correct, i assumed (yes that is the mother of all f..ups) that those were already included in the .gitignore. Maybe an idea to do that?

**Comment by CFTechno** [comment]
requested a new pull

**Pull request merged**
